#ifndef KLVPARSER_H
#define KLVPARSER_H

#include <stdint.h>

typedef enum
{
    KLV_UAS_NULL,// = 0
    KLV_UAS_CHECKSUM,// = 1
    KLV_UAS_TIME_STAMP,// = 2
    KLV_UAS_MISSION_ID,// = 3
    KLV_UAS_TAIL_NUMBER,// = 4
    KLV_UAS_PLATFORM_YAW,// = 5
    KLV_UAS_PLATFORM_PITCH_SHORT,// = 6
    KLV_UAS_PLATFORM_ROLL_SHORT,// = 7
    KLV_UAS_PLATFORM_TAS,// = 8
    KLV_UAS_PLATFORM_IAS,// = 9
    KLV_UAS_PLATFORM_ID,// = 10
    KLV_UAS_SENSOR_ID,// = 11
    KLV_UAS_COORD_SYSTEM,// = 12
    KLV_UAS_SENSOR_LAT,// = 13
    KLV_UAS_SENSOR_LON,// = 14
    KLV_UAS_SENSOR_MSL,// = 15
    KLV_UAS_SENSOR_HFOV,// = 16
    KLV_UAS_SENSOR_VFOV,// = 17
    KLV_UAS_SENSOR_PAN,// = 18
    KLV_UAS_SENSOR_TILT,// = 19
    KLV_UAS_SENSOR_ROLL,// = 20
    KLV_UAS_SLANT_RANGE,// = 21
    KLV_UAS_TARGET_WIDTH,// = 22
    KLV_UAS_IMAGE_LAT,// = 23
    KLV_UAS_IMAGE_LON,// = 24
    KLV_UAS_IMAGE_MSL,// = 25
    KLV_UAS_CORNER1_LAT_OFFSET,// = 26
    KLV_UAS_CORNER1_LON_OFFSET,// = 27
    KLV_UAS_CORNER2_LAT_OFFSET,// = 28
    KLV_UAS_CORNER2_LON_OFFSET,// = 29
    KLV_UAS_CORNER3_LAT_OFFSET,// = 30
    KLV_UAS_CORNER3_LON_OFFSET,// = 31
    KLV_UAS_CORNER4_LAT_OFFSET,// = 32
    KLV_UAS_CORNER4_LON_OFFSET,// = 33
    KLV_UAS_ICING,// = 34
    KLV_UAS_WIND_DIRECTION,// = 35
    KLV_UAS_WIND_SPEED,// = 36
    KLV_UAS_STATIC_PRESSURE,// = 37
    KLV_UAS_DENSITY_ALTITUDE,// = 38
    KLV_UAS_OAT,// = 39
    KLV_UAS_TARGET_LAT,// = 40
    KLV_UAS_TARGET_LON,// = 41
    KLV_UAS_TARGET_MSL,// = 42
    KLV_UAS_TRACK_WIDTH,// = 43
    KLV_UAS_TRACK_HEIGHT,// = 44
    KLV_UAS_TARGET_CE90,// = 45
    KLV_UAS_TARGET_LE90,// = 46
    KLV_UAS_GENERIC_FLAG,// = 47
    KLV_UAS_SECURITY,// = 48
    KLV_UAS_DYNAMIC_PRESSURE,// = 49
    KLV_UAS_ANGLE_OF_ATTACK_SHORT,// = 50
    KLV_UAS_VERTICAL_VELOCITY,// = 51
    KLV_UAS_SIDESLIP_SHORT,// = 52
    KLV_UAS_AIRFIELD_PRESSURE,// = 53
    KLV_UAS_AIRFIELD_ELEVATION,// = 54
    KLV_UAS_HUMIDITY,// = 55
    KLV_UAS_GROUND_SPEED,// = 56
    KLV_UAS_GROUND_RANGE,// = 57
    KLV_UAS_FUEL_REMAINING,// = 58
    KLV_UAS_CALLSIGN,// = 59
    KLV_UAS_WEAPON_LOAD,// = 60
    KLV_UAS_WEAPON_FIRED,// = 61
    KLV_UAS_LASER_PRF_CODE,// = 62
    KLV_UAS_FOV_NAME,// = 63
    KLV_UAS_MAGNETIC_HEADING,// = 64
    KLV_UAS_VERSION,// = 65
    KLV_UAS_TARGET_COVARIANCE,// = 66
    KLV_UAS_ALT_PLATFORM_LAT,// = 67
    KLV_UAS_ALT_PLATFORM_LON,// = 68
    KLV_UAS_ALT_PLATFORM_MSL,// = 69
    KLV_UAS_ALT_PLATFORM_NAME,// = 70
    KLV_UAS_ALT_PLATFORM_HEADING,// = 71
    KLV_UAS_EVENT_START_TIME,// = 72
    KLV_UAS_RVT_LOCAL_SET,// = 73
    KLV_UAS_VMTI,// = 74
    KLV_UAS_SENSOR_HAE,// = 75
    KLV_UAS_ALT_PLATFORM_HAE,// = 76
    KLV_UAS_OPERATIONAL_MODE,// = 77
    KLV_UAS_IMAGE_HAE,// = 78
    KLV_UAS_NORTH_VELOCITY,// = 79
    KLV_UAS_EAST_VELOCITY,// = 80
    KLV_UAS_IMAGE_HORIZON,// = 81
    KLV_UAS_CORNER1_LAT,// = 82
    KLV_UAS_CORNER1_LON,// = 83
    KLV_UAS_CORNER2_LAT,// = 84
    KLV_UAS_CORNER2_LON,// = 85
    KLV_UAS_CORNER3_LAT,// = 86
    KLV_UAS_CORNER3_LON,// = 87
    KLV_UAS_CORNER4_LAT,// = 88
    KLV_UAS_CORNER4_LON,// = 89
    KLV_UAS_PLATFORM_PITCH,// = 90
    KLV_UAS_PLATFORM_ROLL,// = 91
    KLV_UAS_ANGLE_OF_ATTACK,// = 92
    KLV_UAS_SIDESLIP,// = 93
    KLV_UAS_CORE_ID,// = 94
    KLV_UAS_SAR_MOTION_IMAGERY_METADATA, // = 95
    KLV_UAS_TARGET_WIDTH_EXTENDED, // = 96
    KLV_UAS_RANGE_IMAGE_LOCAL_SET, // = 97
    KLV_UAS_GEO_REGISTRATION_LOCAL_SET, // = 98
    KLV_UAS_COMPOSITE_IMAGING_LOCAL_SET, // = 99
    KLV_UAS_SEGMENT_LOCAL_SET, // = 100
    KLV_UAS_AMEND_LOCAL_SET, // = 101
    KLV_UAS_SDCC_FLP, // = 102
    KLV_UAS_DENSITY_ALTITUDE_EXTENDED, // = 103
    KLV_UAS_SENSOR_ELLIPSOID_HEIGHT_EXTENDED, // = 104
    KLV_UAS_ALTERNATE_PLATFORM_ELLIPSOID_HEIGHT_EXTENDED, // = 105
    KLV_UAS_STREAM_DESIGNATOR, // = 106
    KLV_UAS_OPERATIONAL_BASE, // = 107
    KLV_UAS_BROADCAST_SOURCE, // = 108
    KLV_UAS_RANGE_TO_RECOVERY_LOCATION, // = 109
    KLV_UAS_TIME_AIRBORNE, // = 110
    KLV_UAS_PROPULSION_UNIT_SPEED, // = 111
    KLV_UAS_PLATFORM_COURSE_ANGLE, // = 112
    KLV_UAS_ALTITUDE_AGL, // = 113
    KLV_UAS_RADAR_ALTIMETER, // = 114
    KLV_UAS_CONTROL_COMMAND, // = 115
    KLV_UAS_CONTROL_COMMAND_VERIFICATION_LIST, // = 116
    KLV_UAS_SENSOR_AZIMUTH_RATE, // = 117
    KLV_UAS_SENSOR_ELEVATION_RATE, // = 118
    KLV_UAS_SENSOR_ROLL_RATE, // = 119
    KLV_UAS_ON_BOARD_MI_STORAGE_PERCENT_FULL, // = 120
    KLV_UAS_ACTIVE_WAVELENGTH_LIST, // = 121
    KLV_UAS_COUNTRY_CODES, // = 122
    KLV_UAS_NUMBER_OF_NAVSATS_IN_VIEW, // = 123
    KLV_UAS_POSITIONING_METHOD_SOURCE, // = 124
    KLV_UAS_PLATFORM_STATUS, // = 125
    KLV_UAS_SENSOR_CONTROL_MODE, // = 126
    KLV_UAS_SENSOR_FRAME_RATE_PACK, // = 127
    KLV_UAS_WAVELENGTHS_LIST, // = 128
    KLV_UAS_TARGET_ID, // = 129
    KLV_UAS_AIRBASE_LOCATIONS, // = 130
    KLV_UAS_TAKE_OFF_TIME, // = 131
    KLV_UAS_TRANSMISSION_FREQUENCY, // = 132
    KLV_UAS_ON_BOARD_MI_STORAGE_CAPACITY, // = 133
    KLV_UAS_ZOOM_PERCENTAGE, // = 134
    KLV_UAS_COMMUNICATIONS_METHOD, // = 135
    KLV_UAS_LEAP_SECONDS, // = 136
    KLV_UAS_CORRECTION_OFFSET, // = 137
    KLV_UAS_PAYLOAD_LIST, // = 138
    KLV_UAS_ACTIVE_PAYLOADS, // = 139
    KLV_UAS_WEAPONS_STORES, // = 140
    KLV_UAS_WAYPOINT_LIST, // = 141
    KLV_UAS_NUM_ELEMENTS
} KlvUasDataElement_t;

void KlvNewData(const uint8_t *pData, int Length);

double KlvGetValueDouble(KlvUasDataElement_t Element, int *pResult);
int64_t KlvGetValueInt(KlvUasDataElement_t Element, int *pResult);
uint64_t KlvGetValueUInt(KlvUasDataElement_t Element, int *pResult);
const char *KlvGetValueString(KlvUasDataElement_t Element);

void KlvPrintData(void);

#endif // KLVPARSER_H
